### ISSUE TITLE
Is there any way to deploy adonis app to Firebase Hosting?

### ISSUE THREAD

**Issue by mohammadsiddiqui** [adonisjs/adonis-framework#1022]
I am trying to deploy the application to Firebase Functions and since it just need a handler for https.onRequest which can respond.

I tried many things but it's not working out. 

@thetutlage @RomainLanz Do you guys have any pointers for me to acheive this?

I have a feeling it should be pretty easy but I am not able to figure it out. I just need some pointers, if you guys can help then it would be great.

For just a sneak peek, this is the google doc https://firebase.google.com/docs/functions/get-started
 

## Why this feature is required (specific use-cases will be appreciated)?
Firebase

## Have you tried any other work arounds?
DNK

## Are you willing to work on it with little guidance?
Yes

**Comment by klawdyo** [comment]
I also want this funcionality.

**Comment by mohammadsiddiqui** [comment]
@thetutlage @RomainLanz experts any ideas?

**Comment by RomainLanz** [comment]
Hey guys! 👋 

I have never used Firebase myself. Therefore I cannot help that much.

Since it's more a question than an issue with the framework, I recommend you to move this thread in the [forum](https://forum.adonisjs.com/) or in our [Discord Server](https://discord.gg/vDcEjq6). You'll find more people happy to help you with your setup!

Closing this here.
