### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by dubcanada** [adonisjs/adonis-framework#105]
Hello,

I am in need of the Authentication provider, so I figured rather then just build one for myself I would build it and contribute it back. I was reading the Trello card for the Authentication https://trello.com/c/wns5DzT3/28-authentication-provider

Are you wanting to separate it out into it's own repo like you did with the mail provider https://github.com/adonisjs/adonis-mail ? I plan on copying that to start with as that has your driver structure done.

I'm going to start tomorrow, so I'll probably send a pr before the end of this week. At least for basic/session, JWT may take a bit more as I don't need that atm.

Thanks!

**Comment by thetutlage** [comment]
@dubcanada Nice, it will be great to have initial authentication system for Adonis. I am not sure if i would be able to make it the official Auth provider, because the actual one i have in my mind is quite complex. Here is a brief.

1. Authentication system will have UserProviders, whose job will be to validate credentials. Now these can be `username`,`password` or can be a `token`. UserProvider has no idea where the credentials will come from.

2. There will be multiple schemes like `session`, `basic-auth`. Now these scheme knows where to look for credentials.

3. Finally there will a driver which will read credentials from `schemes` and will validate them with the UserProviders. 

Also there will be mechanism for guest logins, which means you can dummy login visitors and once they signup, you can simply join their guest tokens with their user profile. It will be helpful to know what a visitor did before becoming a user.

Obviously you are not bound to implement all these things. But it will be great if you can come up with a normal authentication provider to help others until i come up with the fully fledged one.

**Comment by dubcanada** [comment]
I'll do a basic one for session and basic-auth drivers and leave it at that. I'll try and copy how you do things currently along with the Laravel auth provider and see how it turns out. Hopefully it will work until you do the larger version with JWT and such.

**Comment by thetutlage** [comment]
:+1:

**Comment by thetutlage** [comment]
Issue moved to [adonisjs/adonis-auth #1](https://github.com/adonisjs/adonis-auth/issues/1) via [**ZenHub.io**](https://www.zenhub.io/)
