### ISSUE TITLE
Question about versions

### ISSUE THREAD

**Issue by arempe93** [adonisjs/adonis-framework#1085]
Hi, I'm new to Adonisjs and pretty excited to use it after playing around with the `adonis-api-app` boilerplate. One thing that is confusing me as a new user however is the versions.

It looks like the boilerplate dependencies were updated last year to `adonis-framework: ^5.0.8`, but the docs only go up to version 4.1, but again there is talk in issues of v5 is "coming soon".

So my questions are:
- Checking the releases tab, is `adonis/core` (v2.0) what is being referred to in issues as v5?
- Is `adonis/core` using the `@poppinss` dependencies usable today for a new project?

Thanks in advance, I'd love to use this for my project and make a PR for middleware. But I want to do it in the right place and be able to use it.

**Comment by thetutlage** [comment]
Yeah there is lots of confusion on the versioning of the framework and it's dependencies.

Go through this [thread](https://github.com/adonisjs/rfcs/issues/12#issuecomment-427882012) once and then I am happy to answer more questions

**Comment by arempe93** [comment]
I think the thread explains well the plans for the versioning pattern with the packages. The framework being non-monolithic is a big plus for me as a potential user.

However I think the bulleted concrete questions posed in the OP still stand. Basically, I like the updated code in this repo, and I want to use the new features.

It looks like it's 400+ commits ahead of last release and is being referred to as adonis-core version 2. Which doesn't like up with the rfc discussion. That's where my confusion lies: this repo

**Comment by thetutlage** [comment]
Historically/currently, the AdonisJs version is not the version of any of it's packages, but instead a combination of certain packages formed this artificial version, ie is `4.1` right now.

Now, of-course relying on an artificial version wasn't a good choice at all. So I decided that the main framework version will be driven by a single package called `@adonisjs/core` and documentation will also be written against this version.

The reason you see `@adonisjs/core@2` is coz it is not being officially released. 

To remove all the confusion lemme talk about how it will be after this major release called `v5`.

1. `@adonisjs/core` will be at `5.0.x`. 
2. Documentation will be written against the `major.minor` versions of `@adonisjs/core`.
3. All other packages like `@adonisjs/lucid`, `@adonisjs/websockets` have their own versions.


For now, I do suggest you to use `4.1`, since I have to formalize many things, write proper docs to remove the confusion created by the earlier mess.

**Comment by arempe93** [comment]
Ok, thanks for the clarification. I suppose I will be waiting for adonis-core 5.0 to officially release before migrating my project then. Do you have a general estimate on when that would be? (weeks vs months vs etc)

**Comment by adegbengaagoro** [comment]
@arempe93 I believe you can start utilizing AdonisJS Version 4.1 for your projects. It is very stable and highly functional.

This is what I use for all of my NodeJS projects.

Cheers

**Comment by mrdionjr** [comment]
@thetutlage Hi, thanks for you hard work. It seems like you are doing all the job alone. I can help if you want.
