### ISSUE TITLE
Please add an option to disable cookie encryption

### ISSUE THREAD

**Issue by baybal** [adonisjs/adonis-framework#1166]
Please add an option to disable cookie encryption

**Comment by RomainLanz** [comment]
Hey @baybal! 👋 

Since [you can already defined clear cookies](https://adonisjs.com/docs/4.1/response#_cookies) could you be a bit more specific?

**Comment by baybal** [comment]
Yes, I am aware of plainCookie, I talk bout the case when you need to disable cookie encryption for all code using cookies. Currently, you have to patch all and every piece of code relying on response.cookie  to use plainCookie: session, auth, 3rd party plugins, etc.

**Comment by thetutlage** [comment]
I don't think, I'll ever allow creating unsafe cookies for auth and session data.

Also what's the use case for disabling cookies encryption?

**Comment by baybal** [comment]
Interoperability with other software that checks cookies

**Comment by RomainLanz** [comment]
What's stopping you from decrypting the cookie on other software?

**Comment by baybal** [comment]
We will have to rewrite that and many other softwares to accommodate cookie encryption in a way you do. We can't do that.

**Comment by thetutlage** [comment]
Making auth cookies in-secure isn't the right way to go about it. I am not sure what sort of applications you are running and if you expect a framework to send plain data back to clients, then you need to re-structure your apps for sure.

I will close this issue, since it is not something, I would like to add to the framework. If you have a solid use case around it, then please create an RFC for same and I would love to consider that 😄
