### ISSUE TITLE
[Question] how send data to graphql by test client

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [adonisjs/adonis-framework#1184]
I am studying adonis with graphql support libraries. So far I've been very successful but now I need to create an automated test and for some reason the data is not being forwarded. I researched a lot about stackoverflow, because it's something very specific that I thought of asking this question immediately

the test link is below

https://github.com/carvalhoviniciusluiz/graphql-learn-adonis/blob/8bfb2cd258e3026fa51acd05974ce234004870c0/test/functional/Post.spec.js#L7

also follows a picture of the error i get

![Captura de Tela 2020-01-03 às 10 32 32](https://user-images.githubusercontent.com/22005684/71726059-ae7ef180-2e14-11ea-8e83-b623f30c0020.png)

and the image of the insomnia test returning correctly resolved

![Captura de Tela 2020-01-03 às 09 40 49](https://user-images.githubusercontent.com/22005684/71726073-b76fc300-2e14-11ea-9da7-63076ec16017.png)

Not a question to ask here, but being able to help I appreciate :)

**Comment by thetutlage** [comment]
@carvalhoviniciusluiz I suggest taking the issue to the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?), since AdonisJS doesn't provide any first class package for GraphQL and giving support for community packages is out of the scope of this repo.

Again, not saying, we don't want to help, but the issue tracker is not the right place. Let's discuss this in the forum and I am to help further
