### ISSUE TITLE
Encryption provider generates new string on every call

### ISSUE THREAD

**Issue by lordpixel** [adonisjs/adonis-framework#210]
I want to encrypt my database so I defined some getters/setters on my model like this:

```
  getName (data) {
    data = Encryption.decrypt(data)
    return data
  }
```

Everything is good, data is being encrypted/decrypted on every write/read respectively, however, if I try to search by an encrypted field I would do:

 ```
  let plainText = 'something'
  plainText = Encryption.encrypt(plainText)

  myResult = yield someModel.query().where('name', plainText)
```

I won't find anything because **plainText** is a completely different string than the one in my database.

Is there a workaround to this?

**Comment by thetutlage** [comment]
AdonisJs makes use of [Node.js cyrpto](https://nodejs.org/api/crypto.htm). All encryptions are done using *IV* which requires a random string to keep data secure. You can read more about IV here https://en.wikipedia.org/wiki/Initialization_vector.

Since data is encrypted with the help of a random string, it will generate a different output every time. What you can do is write your own **Encryption service** to encrypted the data without **IV**.

Ideally database data encryption is not something really helpful.

**Comment by lordpixel** [comment]
Hello Virk, I already worked on something to overcome this.
Can I fork Adonis Encryption provider? if so, would you accept a reference in docs to the new provider for those who may want this feature?

Thanks.

**Comment by thetutlage** [comment]
@lordpixel - This is not a very common requirement, so I would suggest to publish it as a separate npm module and let others pull in if they want
