### ISSUE TITLE
Role Based Authentication?

### ISSUE THREAD

**Issue by Nigeltiany** [adonisjs/adonis-framework#242]
Is #230 a touch of Role based Authentication? If so, where is the documentation?
If not. Is there support for Role based authentication?

**Comment by thetutlage** [comment]
@Nigeltiany #230 was just a discussion on passing runtime params to the middleware.

The role based authentication/ACL is not being supported by AdonisJs. But that does not mean, you cannot add it. You will start by writing your own middleware which can grab the currently authenticated user and check their permissions.

I am going to close this issue, since it is not solely related to AdonisJs.
