### ISSUE TITLE
.delete() doesn't appear to work with .limit(1)

### ISSUE THREAD

**Issue by michaeljcalkins** [adonisjs/adonis-framework#263]
I'm trying to delete the first row that matches these sql statement.  No matter where I put the `.limit(1)` all records that match the `.where` are deleted.

What I'm doing:
```javascript
    let result = yield Database
        .table('build_product')
        .where('build_id', buildId)
        .where('product_id', productId)
        // .limit(1)
        .delete()
        .limit(1)
```

What I'm trying to accomplish:
```sql
DELETE FROM `build_product` WHERE `build_id`=1 AND `product_id`=1 LIMIT 1
```

**Comment by thetutlage** [comment]
The issue is with knex itself. I will not even call it an issue, it is a design choice to keep the API consistent across database engines. https://github.com/tgriesser/knex/issues/96

The fix is to add limits here https://github.com/tgriesser/knex/blob/d40e578cadfc12c18ca21fbf436f64f9e36e6079/src/query/compiler.js#L285. Which have been left out, since `postgreSQL` does not have support of `limits` on delete.

**Comment by michaeljcalkins** [comment]
Makes sense, is there a way to run RAW statements via `Database`?

**Comment by thetutlage** [comment]
Yes you can make raw queries using `Database.raw`.  API is almost similar to http://knexjs.org/
