### ISSUE TITLE
Make SessionManager write a lastSeen timestamp

### ISSUE THREAD

**Issue by allanfreitas** [adonisjs/adonis-framework#269]
Hi,

I've created a SessionRedisDriver :)

One thing I've missed was some way to call a 
Session Garbage collector(like PHP have),
to clean the old unused session records.

This will be needed to some other Session Drivers like: database, Redis, Memcache....

Two ways I've propose:
1) SessionManager writes together with every WRITE call a *lastSeen timestamp;
2) An "after Middleware" (after send the response, write it on the session)

One of the alternatives above will help to implement a Session Garbage collector.

What do you think about it?

**- *lastSeen is only the name that I thought now, can be another rsrs.**

Here is the link of my SessionRedisDriver
https://gist.github.com/allanfreitas/c0243e18d00702b641b80169f1fd4b2a

**Comment by thetutlage** [comment]
@allanfreitas Redis session driver already exists in the develop branch and will be release with `v3.1`.

Yes Garbage collector is a nice idea, but it will have a significant impact on performance and ideally Garbage collector only makes sense in case of `file` driver, since we can set expiry for `cookie` and `redis` driver.

Also I will share a command, that you can add to CRON for removing Idle sessions if using the `file` provider.

**Comment by allanfreitas** [comment]
Nice, I've checked just now.

Can you create a *.*.*-alpha|beta|rc.* version?.

If the develop branch already is 3.1.*, 
why does not create alpha|beta or rc releases? 
It's nice to keep up updated.

Or do you have another way to us to do that?

**Comment by thetutlage** [comment]
@allanfreitas Currently the release process is really simple. I work and commit directly in develop, which gets merged into master via release branch.

Also modules like `adonis-framework`, `adonis-lucid` have their own independent versions and combination of these versions defines the actual AdonisJs release.

I didn't want to add other branches for now, since it will be too much of maintenance work me. But once the community will grow, we can talk about a better and more streamline release process. For now a lean and simple process works great for me and gives me more time to work on features.

**Comment by thetutlage** [comment]
@allanfreitas Can we close this issue?

**Comment by allanfreitas** [comment]
Yes, excuse me, this last Days full of work here, i've only check my email now.
