### ISSUE TITLE
Discussion: adonisjs v3 vs laravel 5.3

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#279]
My main reason to move from php (laravel) to nodejs was following:
1) ability to built real-time applications
2) advantages of mongodb over mysql

Initially, I tried Sailsjs because it supports mognodb later tried adonisjs I really liked the framework. Recently Laravel 5.3 has been release and address this real-time feature: https://laravel.com/docs/5.3/broadcasting. Now, I am in little dilemma to continue Nodejs (adonisjs) or switch back to Laravel 5.3

**Comment by obstschale** [comment]
😂 I just came over from Laravel and wanted to learn NodeJS and now you say you might not continue AdonisJS ? 

I am a PHP dev but one thing many say are, that NodeJS and Express are way better in request handling and benchmarks prove that.

So I would love to see AdonisJS continue because, like you said, MongoDB and Real-Time Apps are a big advantage over PHP. I think AdonisJS can shine with good integrations for these features.

**Comment by allanfreitas** [comment]
@webreinvent @obstschale 
The package Mongorito is a ODM for MongoDb,
uses ES6 generators(like Adonisjs).

I cannot test right now, but it seems to be easy to setup it to work with AdonisJS by reading the documentation (http://mongorito.com)
**I will try to create a example this week and put the link here.**

At this moment, 
I think we cannot blow up the core framework with too much features, 
but we can create packages to extend it, 
like the laravel community did :)

I'm using the laravel-oci8 package on 2 projects for a client that uses Oracle, because laravel does not has a official package, and I still wanted to use Laravel :)

I love the syntax and proposal of AdonisJS, and like for laravel I will extend it(with contributing or 3rd packages) to fit my needs.

Let's make it better and spread the word about it :)

**Comment by thetutlage** [comment]
Closing the issue, since it is not actionable. The roadmap is shared on trello https://trello.com/b/yzpqCgdl/adonis-for-humans

**Comment by vedmant** [comment]
Actually Mongodb and Mysql are totally different things, you should use Mongodb only when you don't have relationships, it's very rare cases actually. There is nothing better for relational data than relational databases :) The best if to use both databases in the same project for appropriate needs. Laravel supports Mongodb the same way.

**Comment by thetutlage** [comment]
I agree! Mongodb should be part of stack ( only when required ). I cannot think of use-cases where I will leave SQL and make NoSQL as a core database
