### ISSUE TITLE
Suggestion: form builder accepts global defaults (eg class attribute)

### ISSUE THREAD

**Issue by tremendus** [adonisjs/adonis-framework#351]
Suggest allowing global or _per form instance_  default attributes, esp class. Most CSS frameworks use the same class for each type of input, so code can often be simplified: 
```
// from
{{ form.text('name', null, { class: 'form-input' }) }}
{{ form.text('company', null, { class: 'form-input' }) }}
{{ form.textarea('comment', null, { class: 'form-input' }) }}

// to, eg:
form.defaults.attributes.class = 'form-input'
{{ form.text('name') }}
{{ form.text('company') }}
{{ form.textarea('comment' }}
```
... on large forms, this removes a lot of otherwise redundant duplication

**Comment by thetutlage** [comment]
The purpose of form builder is to make it easier to work with routes and controllers and have DRY form methods and actions with some helpful methods to display form fields.

The best way is to create a macro, since showing `input` fields is not only a matter of classes it also involves surrounding divs and labels too. More on macros here http://adonisjs.com/docs/3.1/views#_macros_imports

```twig
{% macro input(name, title) %}
  <div class="form-field">
    <label>{{ title }}</label>
    {{ form.text(name) }}
  </div>
{% endmacro %}
```

and ofcourse you can improve it as per your needs

**Comment by thetutlage** [comment]
Closing. Feel free to report any new issues
