### ISSUE TITLE
How to Integrate Pusher

### ISSUE THREAD

**Issue by PC-HUB** [adonisjs/adonis-framework#393]
Hey..I am trying to use Pusher in my Back end but i have no idea how can i implement it. I am new to Adonis and i've used Sockets.io in the Back end but for some reason i have to use the Pusher as well and i am totally confused like where do we add all the code for the pusher. For socket.io we creates a class with name sockets in the http directory but for the pusher i have no idea what should be done. A little guide will be very helpful to get me started with it. As for now i thinks we will add all the code in the Socket class itself but still don't know how it will work.
Please help on this since i am totally stuck here 😢

**Comment by thetutlage** [comment]
Pusher has a node.js sdk https://github.com/pusher/pusher-http-node, so you can make use of that. In order to keep it tight, I will recommend wrapping it inside a provider. Reference the below code. 

### providers/Pusher/provider.js
```javascript
'use strict'

const ServiceProvider = require('adonis-fold').ServiceProvider
const Pusher = require('pusher')

class PusherProvider extends ServiceProvider {

  * register () {
    this.app.singleton('MyCompany/Addons/Pusher', (app) => {
      const Env = app.use('Adonis/Src/Env')
      return new Pusher({
        appId: Env.get('PUSHER_APP_ID'),
        key: Env.get('PUSHER_APP_KEY'),
        secret: Env.get('PUSHER_SECRET_KEY')
      })
    })
  }

}

module.exports = PusherProvider
```

Make sure to update the namespace from `MyCompany/Addons/Pusher` to whatever is relevant to you. 

Next you need to define the pusher credentials inside the .env file.

### .env
```
PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_SECRET_KEY=
```

Next you have register your provider, so that it is ready to be used when application boots.

### bootstrap/app.js
```javascript
const path = require('path')

const providers = [
...,
path.join(__dirname, '../providers/Pusher/provider')
]
```

Rest follow pusher docs and you should be good to go

**Comment by PC-HUB** [comment]
thanks a lot @thetutlage ...i will soon try it and let you know.... 😄

**Comment by PC-HUB** [comment]
hey @thetutlage ... thanks a lot.. i am able to use the Pusher now 😃 👍

**Comment by thetutlage** [comment]
Great 👍 

Closing the issue
