### ISSUE TITLE
Implementing this with React, webpack and redux

### ISSUE THREAD

**Issue by golinmarq** [adonisjs/adonis-framework#440]
Do you have any example working this with react, redux and webpack? I don't know where do I have to storage my react app

**Comment by RomainLanz** [comment]
Hey @golinmarq !

Please for this type of question join us on the Gitter instead of creating an issue.

You simply need to render the same view every time you are fetching your application.

Here's some topics that may help you:
- [React with Adonis](http://stackoverflow.com/questions/40627571/react-with-adonis)
- [Render adonis view in React](http://stackoverflow.com/questions/40653117/render-adonis-view-in-react)

**Comment by golinmarq** [comment]
@RomainLanz  thanks for your help! Sorry for the issue
