### ISSUE TITLE
Set class for linkToAction()

### ISSUE THREAD

**Issue by Talraith** [adonisjs/adonis-framework#468]
I'm trying to set the class HTML attribute when using linkToAction() targeting Controller.create and it does not seem to be working.

Code:
`{{ linkToAction('admin/AccountController.create', 'Create Account', {class: 'btn btn-success'}) }}`

Output:
`<a href="admin/accounts/create" >Create</a>`

Please advise.

**Comment by thetutlage** [comment]
I would suggest using the `action` filter http://adonisjs.com/docs/3.2/templating#_action. `linkToAction` is a quick way to create a link without any attributes. 

Also I personally prefer designing the links by selecting the parent element, instead of giving classes to them.

## Example of action file

```html
<a href="{{ 'admin/AccountController.create' | action }}" class="btn btn-success"></a>
```

**Comment by Talraith** [comment]
Perfect!
