### ISSUE TITLE
Inspiration from Laravel

### ISSUE THREAD

**Issue by reshadman** [adonisjs/adonis-framework#5]
Adonis is heavilly inspired by Laravel, whay isnt there any name of laravel in the doc?

**Comment by thetutlage** [comment]
I agree it is , i said that on a thread here [http://qr.ae/RP7kTn](http://qr.ae/RP7kTn) . But i do not want to use Laravel's popularity by saying it everywhere on the official website.

**Comment by quarkmarino** [comment]
As a Laravel developer and new to the vue/nuxt world i really liked your framework, but I would also appreciate some kind of post? idk, that could describe the parallelism between AdonisJS and laravel, that would help to adopt it more quickly, something along "AdonisJS for Laravel developers" or "How do you do that thing that you've done in Laravel so many times but, on AdonisJS", since, in my case I find myself researching every line I don't fully understand (I've realized that my knowledge of node is very thin).
