### ISSUE TITLE
Authentication caching

### ISSUE THREAD

**Issue by niocncn** [adonisjs/adonis-framework#533]
Hello! Can you suggest me the best way to cache authentication check in adonis? I use API Token authentication with Lucid and with every request adonis fetch mysql, what is the best way to cache it?

**Comment by thetutlage** [comment]
Why specific reason you want to cache it?

**Comment by niocncn** [comment]
I want to exclude one request to mysql. In case of user activity not need to check token every time, so why not to push it to cache, for example for 10 minutes. It seems to me the best way to do it in auth middleware, but i did not find how to extend it.

**Comment by thetutlage** [comment]
I am not sure about it, since 1 call to MYSQL is not a big deal for a very important task.

1. What if you revoke the user token? The user still be able to access everything, since we have cached the user details.

2. Also what if the user updates their profile and you are displaying some of the user details from the `auth` object on request. Since it's cached their changes will not reflect.

Caching user authentication has side-effects.

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by BatuhanK** [comment]
@thetutlage Hello, is there any way to achieve this? How can I extend the auth middleware? For example loading user's acl's or other information (from other tables) and cache it (I will manuelly invalidate it, when it's necassary).
