### ISSUE TITLE
AdonisJS auth middleware - redirect if not logged

### ISSUE THREAD

**Issue by Pioruniasty** [adonisjs/adonis-framework#583]
Hi, 

I want to ask how it is possible to redirect user to /login route if he is not logged in using 'auth' middleware ('Adonis/Middleware/Auth')?

**Comment by shekohex** [comment]
you can add another middlewere to handle this , 
and check for the currentUser if exist or it is null
then return to login

**Comment by thetutlage** [comment]
@Pioruniasty You can make use of Error listener to redirect the user. http://adonisjs.com/docs/3.2/error-and-exceptions#_catching_exception

Just use the exception name to write a if block

```js
if (error.name === 'InvalidLoginException') {
  response.redirect('/login')
  return
}
```

**Comment by Pioruniasty** [comment]
Ok, thanks a lot

**Comment by giolf** [comment]
@thetutlage there is a particular reason about
```
response.redirect('/login')
return
```
insead of
```
return response.redirect('/login')
```

**Comment by thetutlage** [comment]
@giolf Sure! In brief, it is more of a personal preference.

Having `return` in a separate line, I am making it clear that `return` statement was used to return early from the function.

Whereas `return response.redirect('/login')` is ambiguous, since you don't know whether it is used for early return or we are returning the output of `response.redirect`.
