### ISSUE TITLE
[Error: Unable to locate null session driver]

### ISSUE THREAD

**Issue by gearsdigital** [adonisjs/adonis-framework#59]
After running `npm start` i got the following error: `[Error: Unable to locate null session driver]`
I intentionally changed nothing related to sessions. It’s also broken when i setup a fresh install using `adonis new`

**Comment by RomainLanz** [comment]
Got it, will commit a hotfix for this.

**Comment by RomainLanz** [comment]
Ok. Waiting for @thetutlage to review this.

The new version of Adonis is using an [`auto-loader`](https://github.com/jwerle/node-auto-loader) to load config file.

Adonis-Lucid use also this package with a [different version](https://github.com/adonisjs/adonis-lucid/blob/master/package.json#L31), [a fork from @thetutlage](https://github.com/thetutlage/node-auto-loader).

In this fork, @thetutlage has made a commit to [preserve file extension](https://github.com/thetutlage/node-auto-loader/commit/75c907108f56da6067fd8fc00fdc31fc5bf67e0c) when loading a directory. So now, when [we load the config directory](https://github.com/adonisjs/adonis-framework/blob/master/src/Config/index.js#L16) it provides us an object with the file extension.

```
// Content of this.config
{
  app.js: [Getter],
  cors.js: [Getter],
  database.js: [Getter],
  session.js: [Getter],
  static.js: [Getter]
}
```

instead of 

```

```
// Desired content of this.config
{
  app: [Getter],
  cors: [Getter],
  database: [Getter],
  session: [Getter],
  static: [Getter]
}
```

**Comment by gearsdigital** [comment]
:+1:

**Comment by thetutlage** [comment]
Fixed with new release. `2.0.5`, i was expecting npm to handle it automatically :disappointed:
