### ISSUE TITLE
Polymorphic Relationships & Validation in Lucid / Adonis 4

### ISSUE THREAD

**Issue by Spazer9** [adonisjs/adonis-framework#660]
I'd really like to give kudos to the people behind Adonis - amazing framework for someone coming from Rails.

Do you guys plan on supporting polymorphic relationships and validation in Adonis 4? I've checked the docs @ http://dev.adonisjs.com/docs/4.0/lucid and I couldn't find something about them.

Thanks!

**Comment by thetutlage** [comment]
Not in the core, but I believe you have build a trait for same, which will require some additional work.

### Why not in core?
Executing string based join queries in SQL is not a good option and polymorphic relations always requires a string based join query

What we afraid of is creating too many database table, which actually is not a bad idea, SQL doesn't hurt when tables count is greater. 

Infact having separate tables makes it easier to optimize things over keeping different types of data within a single table.

I know bunch of companies, dis-allowing polymorphic relations from day one and the reason is same that it has some serious trade-offs.

**Comment by chabib** [comment]
I suggest this reasoning to be added to docs, since there is a big possibility that people who interested to adonis are coming from rails or laravel.

**Comment by thetutlage** [comment]
Nope docs are to learn about what framework offers vs what framework doesn’t offer.

**Comment by chabib** [comment]
fair point

**Comment by Noitidart** [comment]
I was also looking for polymorphic relations. I am coming from Laravel to NodeJS. Thanks for asking the question. The docs didn't have it.

It's awesome to hear that it's not done because of performance. It would be nice if the docs mention "tip" as the framework offers "performant alternative to polymorphic of use the regular relation, and dont write a trait, due to perf". Otherwise people start trying to write a trait just to find out oh, there is a great reason for not having polymorphic, this reason is a feature offered by the framework. Would be awesome to reconsider adding this to the docs. The react docs also have these tidbits, say do not do it X for perf reasons.

**Comment by Ericsonsweah** [comment]
@Spazer9 @chabib @Noitidart @thetutlage You may want to check this out. Someone built it with (with no description) https://github.com/enniel/adonis-lucid-polymorphic

**Comment by Noitidart** [comment]
That is super cool thank you @Ericsonsweah!
