### ISSUE TITLE
project not run

### ISSUE THREAD

**Issue by mimrank** [adonisjs/adonis-framework#672]
install its all depensance and run using instruction `npm run serve:dev`

`p>npm run serve:dev
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve:dev"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! missing script: serve:dev
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\\adonisjs\adonis-framework-develop\npm-debug.log`

**Comment by RomainLanz** [comment]
Hey @mimrank !

Which version are you using?
You must use 4.0.

http://dev.adonisjs.com/docs/4.0/installation

**Comment by mimrank** [comment]
but  4.0 is dev.

**Comment by RomainLanz** [comment]
4.0 is production ready!

It hasn't been released yet because the documentation is not 100% finished, but the API will not change until the final release, so feel free to use it. 😄 

If you have any questions regarding 4.0 that isn't answered within the documentation I recommend you to speak about it in the forum. https://forum.adonisjs.com/

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
