### ISSUE TITLE
Problems with backward compatibility

### ISSUE THREAD

**Issue by enniel** [adonisjs/adonis-framework#768]
Middlewares in versions 4.0.29 and 4.0.28 do not work as expected. In version <= 4.0.28 method handle in middleware return spread args:

```js
class Example {
  async handle ({ auth }, next, first, second, third, ...args) {
     console.log(typeof first) // string
     console.log(typeof second) // string
     console.log(typeof third) // string
  }
}
```

In versions 4.0.29 and 4.0.30 return array:

```js
class Example {
  async handle ({ auth }, next, first, second, third) {
     console.log(typeof first) // array
     console.log(typeof second) // undefined
     console.log(typeof third) // undefined
  }
}
```

**Comment by thetutlage** [comment]
Yup this is the culprit https://github.com/adonisjs/adonis-framework/commit/d1fb5d18c72ac760a9672a7dbac50c35d45ffa7b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R51

I would always want to go with an array over the spread operator. If you are maintaining a package, I suggest expecting an array always, since I recommend everyone to use the latest version, unless it's a major release.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
