### ISSUE TITLE
Content negotiation for JSON not working.

### ISSUE THREAD

**Issue by niallobrien** [adonisjs/adonis-framework#78]
`if (request.is('json','application')) return response.json({hello:"world"})` returns `SyntaxError (400)
Unexpected end of input`.

**Comment by RomainLanz** [comment]
Actually, after some test.

The problem is before hitting the controller method.
The problem occurs when you change the `Content-Type` header.

**Comment by niallobrien** [comment]
Yes, it just seems to fail when you set the `Content-Type` header to `application/json`

**Comment by thetutlage** [comment]
@niallobrien Couple of things here.

1. Get requests should never have `Content-type`. Content type is to define the data client is about to send, so for `GET` requests it is useless.
2. You must use `accepts` instead of `is`, which basically checks for `Accepts` header. Which defines what all content type your client can accept.

```javascript
Route.get('/', function * (request, response) {
  const type = request.accepts(['html', 'json'])
  console.log(request.headers())
  switch (type) {
    case 'json':
      response.json({hello:"world"})
      break
    case 'html':
    default:
      response.send('Hello world')
  }
})
```

Also make sure, the default one's is first inside `accepts` method. Generally tools like `Postman` sets `Accept` to `*/*` which means the first one inside the array will be matched when using `accepts` method.

Finally, the issue was caused by the bodyParser, so i will add more error checking to it, to avoid these kind of situations.

**Comment by thetutlage** [comment]
Created here https://github.com/adonisjs/adonis-middleware/issues/1
