### ISSUE TITLE
Base64 Image Upload

### ISSUE THREAD

**Issue by bryannbarbosa** [adonisjs/adonis-framework#808]
I would like to take the base64 code from an image file, transforming it into a file and uploading that file, is there any functionality in the framework in this regard?

How to proceed?

**Comment by PazzaVlad** [comment]
As far as I know Adonis hasn't such functionality out of the box (because it's not typical task I guess) 

You can upload any binary data, then read stream file (http://adonisjs.com/docs/4.1/file-uploads#_streaming_files) 
convert it to buffer and use something like this: https://gist.github.com/inadarei/4465153

**Comment by thetutlage** [comment]
I believe when you have the base64 code of an image and you are converting it to a file, then all this needs to be happened on the client that is uploading the file.

If your client is a browser app. Then you can simply convert your Base64 code to a `Blob` and send it as `FormData`.

With Adonis, nothing needs to be changed.

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
