### ISSUE TITLE
Adonis how to have dynamic controller and action on routes?

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/adonis-framework#87]
This is a recipe not an issue.

``` javascript
const Route = use('Route')
const Helpers = use('Helpers')
const Ioc = require('adonis-fold').Ioc

Route.any('/:controller/:action', function * (request, response) {
  const controller = request.param('controller')
  const action = request.param('action')
  const controllerPath = `${Helpers.appNameSpace()}/Http/Controllers`
  const controllerInstance = Ioc.makeFunc(`${controllerPath}/${controller}.${action}`)
  yield controllerInstance.instance[controllerInstance.method](request, response)
})
```

**Comment by tinkone** [comment]
This makes infinite sense, convention over configuration. +1 more recipes.

**Comment by thetutlage** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!

**Comment by DerNivel** [comment]
@thetutlage Can you put suchlike recipes on a page in the documentation?

**Comment by vkeusebio** [comment]
I'm curious, why would I want to use or implement this?

**Comment by devdebonair** [comment]
@vkeusebio If I'm not mistaken, this code eliminates the need to manually define routes. Everything would automatically be hooked to controller methods.

**Comment by allanfreitas** [comment]
@devdebonair @vkeusebio Yes, It's will try to match every url to "controller/action" automatically

**Comment by allanfreitas** [comment]
This example code below is working on AdonisJS 3.0.*

<pre>
const Route = use('Route')

const Helpers = use('Helpers')
const Ioc = require('adonis-fold').Ioc

Route.on('/').render('welcome')

Route.get('/post-index', 'PostController.index')

Route.any('/:controller/:action', function * (request, response) {
  const controller = request.param('controller')
  const action = request.param('action')
  const controllerPath = `${Helpers.appNameSpace()}/Http/Controllers`
  const controllerInstance = Ioc.makeFunc(`${controllerPath}/${controller}Controller.${action}`)
  yield controllerInstance.instance[controllerInstance.method](request, response)
})
</pre>

If you want any other custom route, you have to add it before like in the code above.

And I've have to change
`  const controllerInstance = Ioc.makeFunc(`${controllerPath}/${controller}.${action}`)`
to
`  const controllerInstance = Ioc.makeFunc(`${controllerPath}/${controller}**Controller**.${action}`)`

**Note:** Needs the **Controller** keyword to `event/index` work instead of `eventcontroller/index`

**Comment by jamesAtcodeninja** [comment]
How would this work for routes such as `Routes.get('/users', 'UserController.index')` and `Routes.post('/users', 'UserController.create')` ?

**Comment by RomainLanz** [comment]
Hey @jamesAtcodeninja 👋 

If you use this code the route will be `/users/index` & `/users/create`.

**Comment by asantamarian** [comment]
Im trying to use this on version 4 but I just dont getit it please help

`Route.any('/:module/:controller/:action', async ({request, response,params}) => {
  
    const module = params.module
    
    const controller = params.controller
    
    const action = params.action
    
    
    const controllerPath = `App/Controllers/Http/${module}`
    
    const controllerInstance = ioc.makeFunc(`${controllerPath}/${controller}.${action}`)
    
    await controllerInstance.method.apply(controllerInstance.instance,[{request, response}])
  })`

I get this error Cannot read property 'render' of undefined

and here's the controller
`'use strict'

class Guess {
    render ({ request, view }) {
        
        const guessedNumber = Number(request.input('number'))
        const randomNumber = Math.floor(Math.random() * 20) + 1

        return view.render('game', { guessedNumber, randomNumber })
    }
}

module.exports = Guess`

**Comment by asantamarian** [comment]
In case anyone was wondering here's how to do it in version 4

<pre>
Route.any('/:module/:controller/:action',  ({view ,request, response,params}) => {
  
    const module = params.module
    
    const controller = params.controller
    
    const action = params.action
    
    
    const controllerPath = `App/Controllers/Http/${module}`
    
    const url = `${controllerPath}/${controller}.${action}`
    
    const controllerInstance = ioc.makeFunc(url)
    
    return controllerInstance.method.apply(controllerInstance.instance,[{view,request,response}])
    
  })
</pre>
