### ISSUE TITLE
use(...) is not a constructor

### ISSUE THREAD

**Issue by sitthinutk** [adonisjs/adonis-framework#915]
I am sorry if this has been asked, but I don't seem to find related existing issues.

This happened when 2 different .js files try to call `use()` each other.
When I removed either of them from either file, the error went away. 
By the way, I need to use some service from each other, what should I do?

The server responded with **500 - Internal server error**
```
TypeError
use(...) is not a constructor
```

Is this a bug or I understand something incorrectly?
Please also explain the difference between `use()` and `require()` or else paste the URL if your docs already explained that in detail.

## Package version
4.1

## Node.js and npm version
8.9.4 and 5.8.0

## Sample Code (to reproduce the issue)
_LoginService.js_ has this line
```
const RegisterService = new (use('App/Services/RegisterService'))()

// use RegisterService somewhere
```
_RegisterService.js_ has this line
```
const LoginService = new (use('App/Services/LoginService'))()

// use LoginService somewhere
```

**Comment by thetutlage** [comment]
What's the content of `LoginService`

**Comment by sitthinutk** [comment]
It contains general Login logic.
```
'use strict'

// exception
const FitgunException = use('App/Exceptions/FitgunException')

// model
const Database = use('Database')
const Login = use('App/Models/Login')

// service
const RegisterService = new (use('App/Services/RegisterService'))()
const FacebookAPIService = new (use('App/Services/FacebookAPIService'))()

const moment = require('moment')
const { validate } = use('Validator')

class LoginService {
  async validateLoginSchema (login) {
    /// code
  }

  async emailLogin (auth, email, password) {
      // code
  }

  async facebookLogin (auth, facebookToken) {
      // code
  }
}

module.exports = LoginService
```

The point is that **LoginService.js** having this line 
`const RegisterService = new (use('App/Services/RegisterService'))()`
and vice-versa, **RegisterService.js** also having 
`const LoginService = new (use('App/Services/LoginService'))()`

**The error disappear after I either of them from either of file.**

**Comment by mattmallon** [comment]
I'm running into the same issue. I'm not using the new() operator, unlike above. I get the following error regarding my class: AssignmentDueNotification is not a constructor. As soon as I remove the mutual dependency from either class, I no longer get the error. (But both classes do depend on each other, so I end up running into the error that the class dependency I need is undefined.) 

app/Classes/Notifications/NotificationTypes/AssignmentDueNotification.js:
`
const NotificationSetting = use('App/Models/NotificationSetting');

class AssignmentDueNotification {
  async send() {
    const notificationSetting = await NotificationSetting.query().where('notification_type', 'ASSIGNMENT_DUE').firstOrFail();
  //NOTE: it errors out at the line above when I call the send() function on this class
  }
}
module.exports = AssignmentDueNotification;
`

app/Models/NotificationSetting.js:
`
const AssignmentDueNotification = use('App/Classes/Notifications/NotificationTypes/AssignmentDueNotification');
const Model = use('Model');

class NotificationSetting extends Model {
  buildNotificationClass(courseNotificationSetting, course) {
    return new AssignmentDueNotification(this, courseNotificationSetting, course);
  }
}
module.exports = NotificationSetting;
`

My work-around for now is to rely on a Lucid relation to indirectly fetch the dependency I need rather than reference the class directly.

**Comment by thetutlage** [comment]
Node inherently doesn't allow cyclic dependencies and that's the reason you are getting this error

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
