### ISSUE TITLE
route function on view isn't returning correct value for routes with domain defined

### ISSUE THREAD

**Issue by clayderson** [adonisjs/adonis-framework#949]
```
Route.group(() => {
  Route.post('/player', 'ApiPlayerController.save').as('api.v1.player')
}).domain('api.example.com').prefix('/v1').middleware([
  'StoreIdentifier'
])
```

```
Route.group(() => {
  Route.get('/', 'StoreController.show').as('store.index')
}).domain(':address').middleware([
  'StoreIdentifier', 'CheckStoreStatus',
  'StoreViewsGlobalVariable', 'DefineStoreTemplate'
])
```

On view showed in mystore.example.com or mystore.com

```
{{ route('api.v1.player') }}
```

Returning (without complete domain of api)

```
/v1/player
```

Expected value

```
api.example.com/v1/player
```

**Comment by thetutlage** [comment]
You have to manually pass the value of domain, which generating the URL. 

```js
{{ route('api.v1.player', { domain: 'api.example.com' }) }}
```

## Why define the domain manually?
Since the domain property can contain dynamic segments like `:user.example.com`, it is impossible for the method to know the value of the dynamic `:user` segment.

Other way can be to automatically use the domain name, when it is static and discard it when it is dynamic, but that creates confusion. 

To be on the safer side, we decided to accept the domain explicitly as a param

**Comment by clayderson** [comment]
Thank you!

I've tested it now and it does not seem to work.

![captura de tela 2018-09-18 18 14 04](https://user-images.githubusercontent.com/15388584/45716994-fec63780-bb6e-11e8-9129-5271eddd9e04.png)

![captura de tela 2018-09-18 18 14 49](https://user-images.githubusercontent.com/15388584/45716995-fec63780-bb6e-11e8-9a47-47c47890dd76.png)

**Comment by RomainLanz** [comment]
Hey @clayderson! 👋 

You are passing the code @thetutlage gives you as a `string`. Therefore it will not work.

**Comment by clayderson** [comment]
Thank you!
