### ISSUE TITLE
Package update breaking change.

### ISSUE THREAD

**Issue by KindOf** [adonisjs/adonis-framework#993]
## Package version
"@adonisjs/framework": "^5.0.7"

## Node.js and npm version
v8.11.3, 6.4.1

## Sample Code (to reproduce the issue)
```javascript
class UpdateDocFileValidation {
  get rules() {
    return {
      docId: 'required|integer',
      file: 'file|file_ext:png,jpg,jpeg,pdf'
    };
  }
}
```

```javascript
Route.post('/admin/docs/file', 'UserController.updateDocFile')
  .validator('UpdateDocFileValidation')
```
Hey there!
The above code throws an error when I upload a file: `fileExt is not defined as a validation rule`. Looks like I'm using outdated package. But I can't find which one. Updating only @adonis/validator did not help.  Updating all dependencies resolve this issue but I can't do that because it can break other functionality.
 Looks like it was breaking change.
I tried to find release note or something like that about validation rules.
My question: could you please help me to find outdated package to update.

**Comment by thetutlage** [comment]
This is not a breaking change, since you are trying to use a feature, which is part of a newer release of `bodyparser` and `validator` package together.

Breaking change is something, that breaks your existing code (without changing anything) when dependencies are updated.

Also regarding updating packages, it is recommended to upgrade to newer versions of `patch` releases. For example: changing `@adonisjs/framework` from `5.0.7` to `5.0.12` is safe and you should always update it, the patch releases will never include any breaking changes.

**Comment by KindOf** [comment]
Thank you for your response! It was not clear enough what happened when I get those error. I spent some time to investigate. Now I will use suggested update strategy. Hopefully it will help to avoid such problems.
Thank you for your work!

**Comment by brunosousadev** [comment]
Hi, I'm going through the same problem in file validation
where I want to validate a file that can be the following rule:

```
file|file_ext:png,jpg,jpeg,pdf
```
I've already done the frameworks update process as it is in the documentation on this [link](https://adonisjs.com/docs/4.1/upgrade-guide#_getting_started).
